{
 "title": "ee-bench",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "ds", "label": "datasource", "query": "prometheus" },
   {
    "name": "no",
    "label": "node",
    "query": {
     "query": "label_values(kube_node_info{node!~\"node-0|node-1|node-2\"},node)"
    }
   },
   {
    "name": "ns",
    "label": "namespace",
    "query": {
     "query": "label_values(kube_namespace_status_phase{job=\"kube-state-metrics\"},namespace)"
    }
   },
   {
    "name": "sensor",
    "label": "Sensor",
    "query": {
     "query": "label_values(node_ipmi_power_watts,sensor)"
    }
   },
   {
    "name": "start_traces",
    "query": {
     "query": "query_result(max(mub_experiment_start_time_traces_seconds*1000))"
    }
   },
   {
    "name": "experiment",
    "query": {
     "query": "label_values(mub_experiment_start_time_deployments_seconds,experiment_id)"
    }
   },
   {
    "name": "finished_experiment",
    "query": {
     "query": "query_result(max(mub_experiment_finished_time_seconds{experiment_id=\"$experiment\"}) * 1000)"
    }
   },
   { "name": "result_dash_title", "query": "ee-bench-results" },
   { "name": "result_dash_uid", "query": "aec2zsgqtnuo0e" }
  ]
 },
 "panels": [
  { "title": "Results", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Time",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(max(mub_experiment_finished_time_seconds{experiment_id=\"$experiment\"}) - max(mub_experiment_start_time_traces_seconds{experiment_id=\"$experiment\"})) / 60",
     "legendFormat": "TS"
    }
   ]
  },
  {
   "title": "Result Dashboard",
   "type": "text",
   "description": "Generates a link to the result Dashboard when END timestamp is present",
   "gridPos": { "h": 6, "w": 19, "x": 5, "y": 1 },
   "options": {
    "content": "When the line below shows a timestamp you can \n\n    ${finished_experiment}\n\nOpen the link below **in a new tab/window** to the result dashboard with the timeframe to cover the exact experiment durations.\n\n<a href=\"./d/${result_dash_uid}/${result_dash_title}?orgId=1&from=${start_traces}&to=${finished_experiment}&timezone=utc\" target=\"_blank\">Result Dashboard</a>\n\n\n"
   }
  },
  { "title": "Experiment META", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "START Deployments",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(mub_experiment_start_time_deployments_seconds{experiment_id=\"$experiment\"}) * 1000",
     "legendFormat": "TS"
    }
   ]
  },
  {
   "title": "START TRACES",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(mub_experiment_start_time_traces_seconds{experiment_id=\"$experiment\"}) * 1000",
     "legendFormat": "TS"
    }
   ]
  },
  {
   "title": "END ESTIMATE",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(mub_experiment_finished_time_estimated_seconds{experiment_id=\"$experiment\"}) * 1000",
     "legendFormat": "TS"
    }
   ]
  },
  {
   "title": "END FINISHED",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(mub_experiment_finished_time_seconds{experiment_id=\"$experiment\"}) * 1000",
     "legendFormat": "TS"
    }
   ]
  },
  { "title": "Progress", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Deployed MS",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(mub_deployed_services_total{experiment_id=\"$experiment\"})",
     "legendFormat": "DEPLOYED"
    },
    {
     "expr": "mub_experiment_ms_count{experiment_id=\"$experiment\"}",
     "legendFormat": "ALL"
    }
   ]
  },
  {
   "title": "Processed Requests",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mub_processed_requests_total{experiment_id=\"$experiment\"}",
     "legendFormat": "PROCESSED"
    },
    {
     "expr": "mub_experiment_trace_count{experiment_id=\"$experiment\"}",
     "legendFormat": "ALL"
    }
   ]
  },
  {
   "title": "Pending Requests",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mub_pending_requests{experiment_id=\"$experiment\"}",
     "legendFormat": "PENDING"
    }
   ]
  },
  {
   "title": "Request Timing Errors",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mub_timing_error_requests_total{experiment_id=\"$experiment\"}",
     "legendFormat": "ERROR"
    },
    {
     "expr": "mub_experiment_trace_count{experiment_id=\"$experiment\"}",
     "legendFormat": "ALL"
    }
   ]
  },
  { "title": "$no", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 }, "repeat": "no" },
  {
   "title": "Power Constumption (Watt)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "node_ipmi_power_watts{node_name=~\"$no\", sensor=~\"$sensor\"}",
     "legendFormat": "{{node_name}} {{sensor}}"
    }
   ]
  },
  {
   "title": "Service delay",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum by (pod) (increase(mub_request_processing_latency_milliseconds_sum{node=~\"$no\", namespace=~\"$ns\"}[2m])) / sum by (pod) (increase(mub_request_processing_latency_milliseconds_count{node=~\"$no\", namespace=~\"$ns\"}[2m]))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Internal Service delay",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum by (pod) (increase(mub_internal_processing_latency_milliseconds_sum{node=~\"$no\", namespace=~\"$ns\"}[2m])) / sum by (pod) (increase(mub_internal_processing_latency_milliseconds_count{node=~\"$no\", namespace=~\"$ns\"}[2m]))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", namespace=~\"$ns\", node=~\"$no\"}[30s])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Memory Usage (w/o cache)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", cluster=\"\", namespace=~\"$ns\", node=~\"$no\"}) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}
{
 "title": "ee-bench-results",
 "time": { "from": "now-60m", "to": "now" },
 "templating": {
  "list": [
   { "name": "ds", "label": "datasource", "query": "prometheus" },
   {
    "name": "sensor",
    "label": "Sensor",
    "query": {
     "query": "label_values(node_ipmi_power_watts,sensor)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Request Timing Errors",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 7, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(mub_timing_error_requests_total)",
     "legendFormat": "ERROR"
    },
    {
     "expr": "max(mub_experiment_trace_count)",
     "legendFormat": "ALL"
    },
    { "expression": "$A / $B", "reducer": "mean", "type": "math" }
   ]
  },
  {
   "title": "Time Taken (seconds)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expression": "(${__to} - ${__from})/1000", "type": "math" }
   ]
  },
  {
   "title": "Energy Consumption",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(avg_over_time(node_ipmi_power_watts{sensor=~\"$sensor\", node_name!~\"node-0|node-1|node-2\"}[10s]))",
     "legendFormat": "watt_avg {{node_name}}"
    },
    {
     "expression": "(${__to} - ${__from})/1000/3600",
     "type": "math"
    },
    { "expression": "$DUR_HOUR * $WATT", "type": "math" }
   ]
  },
  {
   "title": "Total Response Time (seconds)",
   "type": "stat",
   "description": "sum of all response times from runner perspective",
   "gridPos": { "h": 4, "w": 7, "x": 7, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(mub_request_latency_milliseconds_sum) / 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Score Formula",
   "type": "text",
   "gridPos": { "h": 4, "w": 7, "x": 0, "y": 8 },
   "options": {
    "content": "```\r\n            10,000,000\r\n--------------------------------------\r\nenergy * total response time (seconds)\r\n```"
   }
  },
  {
   "title": "Score",
   "type": "stat",
   "description": "10,000,000 / (energy * total response time seconds)",
   "gridPos": { "h": 4, "w": 7, "x": 7, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(avg_over_time(node_ipmi_power_watts{sensor=~\"$sensor\", node_name!~\"node-0|node-1|node-2\"}[10s]))",
     "legendFormat": "watt_avg {{node_name}}"
    },
    {
     "expression": "(${__to} - ${__from})/1000/3600",
     "type": "math"
    },
    { "expression": "$DUR_HOUR * $WATT", "type": "math" },
    {
     "expr": "sum(mub_request_latency_milliseconds_sum) / 1000",
     "legendFormat": "__auto"
    },
    {
     "expression": "10000000 / (${Wh} * ${TRTseconds})",
     "type": "math"
    }
   ]
  }
 ]
}
{
 "title": "µBench-dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Service delay",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum by (app_name) (increase(mub_request_processing_latency_milliseconds_sum{}[2m])) / sum by (app_name) (increase(mub_request_processing_latency_milliseconds_count{}[2m]))",
     "legendFormat": "{{destination_app}}"
    }
   ]
  },
  {
   "title": "Service rate (req/s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (app_name) (rate(mub_internal_processing_latency_milliseconds_count{}[2m]))/1000",
     "legendFormat": "{{destination_app}}"
    }
   ]
  },
  {
   "title": "Internal service delay ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum by (app_name) (increase(mub_internal_processing_latency_milliseconds_sum{}[2m])) / sum by (app_name) (increase(mub_internal_processing_latency_milliseconds_count{}[2m]))",
     "legendFormat": "{{app_name}}"
    }
   ]
  },
  {
   "title": "External service delay ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum by (app_name) (increase(mub_external_processing_latency_milliseconds_sum{}[2m])) / sum by (app_name) (increase(mub_external_processing_latency_milliseconds_count{}[2m]))",
     "legendFormat": "{{app_name}}"
    }
   ]
  },
  {
   "title": "CPU x service",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum by (pod) (increase(container_cpu_usage_seconds_total{pod=~\"ms-[0-9].*\"}[2m])/120)",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Memory x service",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "sum by (pod) (sum_over_time(container_memory_usage_bytes{pod=~\"ms-[0-9].*\"}[2m]) / count_over_time(container_memory_usage_bytes{pod=~\"ms-[0-9].*\"}[2m])) / 1e6",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "CPU x node",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "sum by (node) (rate(container_cpu_usage_seconds_total[2m]))",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "CPU usage / CPU requested x Service",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (pod) (increase(container_cpu_usage_seconds_total{pod=~\"ms-[0-9].*\"}[2m])) / (120 * sum by (pod) (kube_pod_container_resource_requests{pod=~\"ms-[0-9].*\"}))",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "CPU by namespace",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "sum(increase(container_cpu_usage_seconds_total[2m])) by (namespace) / 120",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Memory of Cluster",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "sum (sum_over_time(container_memory_working_set_bytes{pod=~\"ms-[0-9].*\"}[2m]) / count_over_time(container_memory_working_set_bytes{pod=~\"ms-[0-9].*\"}[2m])) / 1e6",
     "legendFormat": "Cluster Memory"
    }
   ]
  },
  {
   "title": "CPU req x Node",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "sum by (node) (kube_pod_container_resource_requests{pod=~\"ms-[0-9].*\", resource=\"cpu\"})",
     "legendFormat": "{{node}}"
    }
   ]
  }
 ]
}