{
 "title": "ee-bench-results",
 "time": { "from": "now-60m", "to": "now" },
 "templating": {
  "list": [
   { "name": "ds", "label": "datasource", "query": "prometheus" },
   {
    "name": "sensor",
    "label": "Sensor",
    "query": {
     "query": "label_values(node_ipmi_power_watts,sensor)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Request Timing Errors",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 7, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(mub_timing_error_requests_total)",
     "legendFormat": "ERROR"
    },
    {
     "expr": "max(mub_experiment_trace_count)",
     "legendFormat": "ALL"
    },
    { "expression": "$A / $B", "reducer": "mean", "type": "math" }
   ]
  },
  {
   "title": "Time Taken (seconds)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expression": "(${__to} - ${__from})/1000", "type": "math" }
   ]
  },
  {
   "title": "Energy Consumption",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(avg_over_time(node_ipmi_power_watts{sensor=~\"$sensor\", node_name!~\"node-0|node-1|node-2\"}[10s]))",
     "legendFormat": "watt_avg {{node_name}}"
    },
    {
     "expression": "(${__to} - ${__from})/1000/3600",
     "type": "math"
    },
    { "expression": "$DUR_HOUR * $WATT", "type": "math" }
   ]
  },
  {
   "title": "Total Response Time (seconds)",
   "type": "stat",
   "description": "sum of all response times from runner perspective",
   "gridPos": { "h": 4, "w": 7, "x": 7, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(mub_request_latency_milliseconds_sum) / 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Score Formula",
   "type": "text",
   "gridPos": { "h": 4, "w": 7, "x": 0, "y": 8 },
   "options": {
    "content": "```\r\n            10,000,000\r\n--------------------------------------\r\nenergy * total response time (seconds)\r\n```"
   }
  },
  {
   "title": "Score",
   "type": "stat",
   "description": "10,000,000 / (energy * total response time seconds)",
   "gridPos": { "h": 4, "w": 7, "x": 7, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(avg_over_time(node_ipmi_power_watts{sensor=~\"$sensor\", node_name!~\"node-0|node-1|node-2\"}[10s]))",
     "legendFormat": "watt_avg {{node_name}}"
    },
    {
     "expression": "(${__to} - ${__from})/1000/3600",
     "type": "math"
    },
    { "expression": "$DUR_HOUR * $WATT", "type": "math" },
    {
     "expr": "sum(mub_request_latency_milliseconds_sum) / 1000",
     "legendFormat": "__auto"
    },
    {
     "expression": "10000000 / (${Wh} * ${TRTseconds})",
     "type": "math"
    }
   ]
  }
 ]
}