{
 "title": "ee-bench",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "ds", "label": "datasource", "query": "prometheus" },
   {
    "name": "no",
    "label": "node",
    "query": {
     "query": "label_values(kube_node_info,node)"
    }
   },
   {
    "name": "ns",
    "label": "namespace",
    "query": {
     "query": "label_values(kube_namespace_status_phase{job=\"kube-state-metrics\"},namespace)"
    }
   },
   {
    "name": "sensor",
    "label": "Sensor",
    "query": {
     "query": "label_values(node_ipmi_power_watts,sensor)"
    }
   },
   {
    "name": "start_traces",
    "query": {
     "query": "query_result(max(mub_experiment_start_time_traces_seconds*1000))"
    }
   },
   {
    "name": "finished_experiment",
    "query": {
     "query": "query_result(max(mub_experiment_finished_time_seconds*1000))"
    }
   },
   {
    "name": "start_deploy",
    "query": {
     "query": "query_result(max(mub_experiment_start_time_deployments_seconds*1000))"
    }
   },
   { "name": "duration", "query": { "query": "label_values()" } }
  ]
 },
 "panels": [
  {
   "title": "Set Timeframe",
   "type": "text",
   "gridPos": { "h": 3, "w": 9, "x": 0, "y": 0 },
   "options": {
    "content": "Click the link below to switch the timeframe to cover the exact experiment durations\n\n[Result Time Frame](./d/eeayt2o0nyq68b/ee-bench-copy?orgId=1&from=${start_traces}&to=${finished_experiment}&timezone=utc)"
   }
  },
  { "title": "Results", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "Total Time",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(max(mub_experiment_finished_time_seconds) - max(mub_experiment_start_time_traces_seconds)) / 60",
     "legendFormat": "TS"
    }
   ]
  },
  { "title": "Experiment META", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "START Deployments",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(mub_experiment_start_time_deployments_seconds) * 1000",
     "legendFormat": "TS"
    }
   ]
  },
  {
   "title": "START TRACES",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(mub_experiment_start_time_traces_seconds) * 1000",
     "legendFormat": "TS"
    }
   ]
  },
  {
   "title": "END ESTIMATE",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(mub_experiment_finished_time_estimated_seconds) * 1000",
     "legendFormat": "TS"
    }
   ]
  },
  {
   "title": "END FINISHED",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(mub_experiment_finished_time_seconds) * 1000",
     "legendFormat": "TS"
    }
   ]
  },
  { "title": "Progress", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Deployed MS",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(mub_deployed_services_total)",
     "legendFormat": "DEPLOYED"
    },
    { "expr": "mub_experiment_ms_count", "legendFormat": "ALL" }
   ]
  },
  {
   "title": "Processed Requests",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "mub_processed_requests_total", "legendFormat": "PROCESSED" },
    { "expr": "mub_experiment_trace_count", "legendFormat": "ALL" }
   ]
  },
  {
   "title": "Pending Requests",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "mub_pending_requests", "legendFormat": "PENDING" }
   ]
  },
  {
   "title": "Request Timing Errors",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mub_timing_error_requests_total",
     "legendFormat": "ERROR"
    },
    { "expr": "mub_experiment_trace_count", "legendFormat": "ALL" }
   ]
  },
  { "title": "$no", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 }, "repeat": "no" },
  {
   "title": "Power Constumption (Watt)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "node_ipmi_power_watts{node_name=~\"$no\", sensor=~\"$sensor\"}",
     "legendFormat": "{{node_name}} {{sensor}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", namespace=~\"$ns\", node=~\"$no\"}[30s])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Memory Usage (w/o cache)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", cluster=\"\", namespace=~\"$ns\", node=~\"$no\"}) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}